// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloDB;

namespace ModeloDB.Migrations
{
    [DbContext(typeof(TarjetaContex))]
    [Migration("20220121003248_TarjetaR")]
    partial class TarjetaR
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidades.Entidades.Calculos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Factur36")
                        .HasColumnType("real");

                    b.Property<float>("calculo")
                        .HasColumnType("real");

                    b.Property<float>("rol12")
                        .HasColumnType("real");

                    b.Property<float>("rol24")
                        .HasColumnType("real");

                    b.Property<int?>("rolPagoid")
                        .HasColumnType("int");

                    b.Property<int?>("rolPagosPublicaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("rolPagoid");

                    b.HasIndex("rolPagosPublicaid");

                    b.ToTable("Calculos");
                });

            modelBuilder.Entity("Entidades.Entidades.Deudas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentSolicitudid")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeuda")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CurrentSolicitudid");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("Entidades.Entidades.Factura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calculos_Id")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSolicitudid")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Solicitudid")
                        .HasColumnType("int");

                    b.Property<int>("factura")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Calculos_Id")
                        .IsUnique();

                    b.HasIndex("Solicitudid");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Entidades.Entidades.Prerequsitos", b =>
                {
                    b.Property<int>("RolPagoId")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<int>("RolPagoPublicaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("RolPagoId", "FacturaId", "RolPagoPublicaId", "UsuarioId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("RolPagoPublicaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prerequsitos");
                });

            modelBuilder.Entity("Entidades.Entidades.RolPago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentSolicitudid")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRol")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Solicitudid")
                        .HasColumnType("int");

                    b.Property<int>("rolPago")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Solicitudid");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Entidades.Entidades.RolPagosPublica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentSolicitudid")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRol")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Solicitudid")
                        .HasColumnType("int");

                    b.Property<int>("rolPagoPublica")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Solicitudid");

                    b.ToTable("RolPublica");
                });

            modelBuilder.Entity("Entidades.Entidades.Solicitud", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ingresos")
                        .HasColumnType("int");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Entidades.Entidades.Tarjeta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentSolicitudid")
                        .HasColumnType("int");

                    b.Property<string>("TarjetaName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CurrentSolicitudid");

                    b.ToTable("Tarjetas");
                });

            modelBuilder.Entity("Entidades.Entidades.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSolicitudid")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CurrentSolicitudid");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Entidades.Entidades.Calculos", b =>
                {
                    b.HasOne("Entidades.Entidades.RolPago", "rolPago")
                        .WithMany()
                        .HasForeignKey("rolPagoid");

                    b.HasOne("Entidades.Entidades.RolPagosPublica", "rolPagosPublica")
                        .WithMany()
                        .HasForeignKey("rolPagosPublicaid");

                    b.Navigation("rolPago");

                    b.Navigation("rolPagosPublica");
                });

            modelBuilder.Entity("Entidades.Entidades.Deudas", b =>
                {
                    b.HasOne("Entidades.Entidades.Solicitud", "Solicitud")
                        .WithMany("Deudas")
                        .HasForeignKey("CurrentSolicitudid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Entidades.Entidades.Factura", b =>
                {
                    b.HasOne("Entidades.Entidades.Calculos", "Calculos")
                        .WithOne("Facturas")
                        .HasForeignKey("Entidades.Entidades.Factura", "Calculos_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("Solicitudid");

                    b.Navigation("Calculos");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Entidades.Entidades.Prerequsitos", b =>
                {
                    b.HasOne("Entidades.Entidades.Factura", "Factura")
                        .WithMany("Prerequsitos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.RolPago", "RolPago")
                        .WithMany("Prerequsitos")
                        .HasForeignKey("RolPagoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.RolPagosPublica", "RolPagosPublica")
                        .WithMany("Prerequsitos")
                        .HasForeignKey("RolPagoPublicaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entidades.Entidades.Usuario", "Usuario")
                        .WithMany("Prerequsitos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("RolPago");

                    b.Navigation("RolPagosPublica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entidades.Entidades.RolPago", b =>
                {
                    b.HasOne("Entidades.Entidades.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("Solicitudid");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Entidades.Entidades.RolPagosPublica", b =>
                {
                    b.HasOne("Entidades.Entidades.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("Solicitudid");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Entidades.Entidades.Tarjeta", b =>
                {
                    b.HasOne("Entidades.Entidades.Solicitud", "Solicitud")
                        .WithMany("Tarjetas")
                        .HasForeignKey("CurrentSolicitudid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Entidades.Entidades.Usuario", b =>
                {
                    b.HasOne("Entidades.Entidades.Solicitud", "Solicitud")
                        .WithMany("Usuarios")
                        .HasForeignKey("CurrentSolicitudid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Entidades.Entidades.Calculos", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Entidades.Entidades.Factura", b =>
                {
                    b.Navigation("Prerequsitos");
                });

            modelBuilder.Entity("Entidades.Entidades.RolPago", b =>
                {
                    b.Navigation("Prerequsitos");
                });

            modelBuilder.Entity("Entidades.Entidades.RolPagosPublica", b =>
                {
                    b.Navigation("Prerequsitos");
                });

            modelBuilder.Entity("Entidades.Entidades.Solicitud", b =>
                {
                    b.Navigation("Deudas");

                    b.Navigation("Tarjetas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Entidades.Entidades.Usuario", b =>
                {
                    b.Navigation("Prerequsitos");
                });
#pragma warning restore 612, 618
        }
    }
}
